###
# Find All Users
GET  http://localhost:3001/users

###
# Find User By Id
GET  http://localhost:3001/users/1

###
# Create User
POST  http://localhost:3001/users
Content-Type: application/json

{
    "email": "example@email.com",
    "password": "password"
}

###
# Modify User By Id
PUT  http://localhost:3001/users/1
Content-Type: application/json

{
    "email": "example@email.com",
    "password": "password"
}

###
# Delete User By Id
DELETE  http://localhost:3001/users/6201a4c0025ada2a50124b43
